/*
f * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anusha.ssupermarket;


import static anusha.ssupermarket.Customer_UI.user;
import java.awt.event.KeyEvent;
import java.awt.event.KeyAdapter;
import javax.swing.*;
import java.awt.*;
import java.io.*;

import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;


/**
 *
 * @author faraz
 */
public class Customer_edible extends javax.swing.JFrame {

    /**
     * Creates new form CustomreUI
     */
    public static String user;
    public Customer_edible(String Userinfo,cartThread t1,int counts) {
        initComponents(); 
    user = Userinfo;
    cartt1 = t1;
count=counts;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        sidebar = new javax.swing.JPanel();
        shirt = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        All = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        pant = new javax.swing.JPanel();
        name3 = new javax.swing.JLabel();
        jewellery = new javax.swing.JPanel();
        name4 = new javax.swing.JLabel();
        Cart = new javax.swing.JPanel();
        name5 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        name7 = new javax.swing.JLabel();
        edible = new javax.swing.JPanel();
        name6 = new javax.swing.JLabel();
        TopBar = new javax.swing.JPanel();
        closewindow = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        minimize = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        shopping = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        allitems3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        allitems2 = new javax.swing.JPanel();
        Sprite = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pepsi = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Drpepper = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        doritos = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        redbull = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        wavy = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Lays = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 100, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(23, 35, 51));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shirt.setBackground(new java.awt.Color(23, 35, 51));
        shirt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                shirtMousePressed(evt);
            }
        });
        shirt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(242, 242, 242));
        name1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_shirt_30px.png"))); // NOI18N
        name1.setText("Shirts");
        shirt.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 73, 34));

        sidebar.add(shirt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 50));

        All.setBackground(new java.awt.Color(23, 35, 51));
        All.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AllMousePressed(evt);
            }
        });
        All.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name2.setForeground(new java.awt.Color(242, 242, 242));
        name2.setText("ALL");
        All.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 73, 34));

        sidebar.add(All, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        pant.setBackground(new java.awt.Color(23, 35, 51));
        pant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pantMousePressed(evt);
            }
        });
        pant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name3.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name3.setForeground(new java.awt.Color(242, 242, 242));
        name3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_pajama_pants_30px.png"))); // NOI18N
        name3.setText("Pants");
        pant.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 73, 34));

        sidebar.add(pant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 50));

        jewellery.setBackground(new java.awt.Color(23, 35, 51));
        jewellery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jewelleryMousePressed(evt);
            }
        });
        jewellery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name4.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name4.setForeground(new java.awt.Color(242, 242, 242));
        name4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_ring_side_view_30px.png"))); // NOI18N
        name4.setText("Jewellery");
        jewellery.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 34));

        sidebar.add(jewellery, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 110, 50));

        Cart.setBackground(new java.awt.Color(23, 35, 51));
        Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CartMousePressed(evt);
            }
        });
        Cart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name5.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name5.setForeground(new java.awt.Color(242, 242, 242));
        name5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_Shopping_Cart_30px.png"))); // NOI18N
        name5.setText("Cart");
        Cart.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 34));

        sidebar.add(Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 110, 50));

        logout.setBackground(new java.awt.Color(23, 35, 51));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name7.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name7.setForeground(new java.awt.Color(242, 242, 242));
        name7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_logout_30px.png"))); // NOI18N
        logout.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        sidebar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 90, 50));

        edible.setBackground(new java.awt.Color(41, 57, 80));
        edible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                edibleMousePressed(evt);
            }
        });
        edible.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name6.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name6.setForeground(new java.awt.Color(242, 242, 242));
        name6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_group_of_fruits_30px.png"))); // NOI18N
        name6.setText("Edible");
        edible.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, 80, 34));

        sidebar.add(edible, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 110, 50));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 750, -1));

        TopBar.setBackground(new java.awt.Color(77, 128, 216));
        TopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closewindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closewindowMousePressed(evt);
            }
        });
        closewindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_close_window_45px.png"))); // NOI18N
        closewindow.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 50, 50));

        TopBar.add(closewindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 30, 30));

        minimize.setInheritsPopupMenu(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeMousePressed(evt);
            }
        });
        minimize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_minimize_window_45px_1.png"))); // NOI18N
        minimize.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 50, 50));

        TopBar.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 30, 30));

        getContentPane().add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        allitems3.setBackground(new java.awt.Color(62, 120, 207));

        allitems2.setBackground(new java.awt.Color(62, 120, 207));
        allitems2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sprite.setOpaque(false);
        Sprite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SpriteMousePressed(evt);
            }
        });
        Sprite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel32.setBackground(new java.awt.Color(62, 120, 207));

        jLabel50.setIcon(new javax.swing.ImageIcon("C:\\Users\\faraz\\OneDrive\\Documents\\NetBeansProjects\\Anusha'sSupermarket\\src\\anusha\\ssupermarket\\sprite.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Sprite.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel23.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Sprite 1.5L");
        Sprite.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, 130, 16));

        jLabel24.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Rs: 130");
        Sprite.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, 130, 16));

        allitems2.add(Sprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        pepsi.setOpaque(false);
        pepsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pepsiMousePressed(evt);
            }
        });
        pepsi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(62, 120, 207));

        jLabel52.setIcon(new javax.swing.ImageIcon("C:\\Users\\faraz\\OneDrive\\Documents\\NetBeansProjects\\Anusha'sSupermarket\\src\\anusha\\ssupermarket\\pepsi.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pepsi.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel27.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Pepsi 500ml");
        pepsi.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, 130, 16));

        jLabel28.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Rs: 60");
        pepsi.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, 130, 16));

        allitems2.add(pepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        Drpepper.setOpaque(false);
        Drpepper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DrpepperMousePressed(evt);
            }
        });
        Drpepper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel36.setBackground(new java.awt.Color(62, 120, 207));

        jLabel51.setIcon(new javax.swing.ImageIcon("C:\\Users\\faraz\\OneDrive\\Documents\\NetBeansProjects\\Anusha'sSupermarket\\src\\anusha\\ssupermarket\\drpepper.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Drpepper.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel29.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Dr.Pepper");
        Drpepper.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, 130, 16));

        jLabel30.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Rs: 200");
        Drpepper.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, 130, 16));

        allitems2.add(Drpepper, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        doritos.setOpaque(false);
        doritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                doritosMousePressed(evt);
            }
        });
        doritos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel38.setBackground(new java.awt.Color(62, 120, 207));

        jLabel53.setIcon(new javax.swing.ImageIcon("C:\\Users\\faraz\\OneDrive\\Documents\\NetBeansProjects\\Anusha'sSupermarket\\src\\anusha\\ssupermarket\\doritos.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        doritos.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel31.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Doritos");
        doritos.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, 130, 16));

        jLabel32.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Rs: 150");
        doritos.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, 130, 16));

        allitems2.add(doritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        redbull.setOpaque(false);
        redbull.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                redbullMousePressed(evt);
            }
        });
        redbull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel40.setBackground(new java.awt.Color(62, 120, 207));

        jLabel56.setIcon(new javax.swing.ImageIcon("C:\\Users\\faraz\\OneDrive\\Documents\\NetBeansProjects\\Anusha'sSupermarket\\src\\anusha\\ssupermarket\\redbull.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        redbull.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel35.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("RedBull");
        redbull.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, 130, 16));

        jLabel36.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Rs: 400");
        redbull.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, 130, 16));

        allitems2.add(redbull, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        wavy.setOpaque(false);
        wavy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wavyMousePressed(evt);
            }
        });
        wavy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel42.setBackground(new java.awt.Color(62, 120, 207));

        jLabel54.setIcon(new javax.swing.ImageIcon("C:\\Users\\faraz\\OneDrive\\Documents\\NetBeansProjects\\Anusha'sSupermarket\\src\\anusha\\ssupermarket\\wavy.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        wavy.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel37.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Wavy BBQ");
        wavy.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, 130, 16));

        jLabel38.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Rs: 40");
        wavy.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, 130, 16));

        allitems2.add(wavy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Lays.setOpaque(false);
        Lays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LaysMousePressed(evt);
            }
        });
        Lays.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel44.setBackground(new java.awt.Color(62, 120, 207));

        jLabel55.setIcon(new javax.swing.ImageIcon("C:\\Users\\faraz\\OneDrive\\Documents\\NetBeansProjects\\Anusha'sSupermarket\\src\\anusha\\ssupermarket\\laysmasala.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Lays.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel39.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Lays Masla");
        Lays.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, 130, 16));

        jLabel63.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Rs: 40");
        Lays.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, 130, 16));

        allitems2.add(Lays, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jScrollPane6.setViewportView(allitems2);

        javax.swing.GroupLayout allitems3Layout = new javax.swing.GroupLayout(allitems3);
        allitems3.setLayout(allitems3Layout);
        allitems3Layout.setHorizontalGroup(
            allitems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );
        allitems3Layout.setVerticalGroup(
            allitems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );

        jScrollPane7.setViewportView(allitems3);

        javax.swing.GroupLayout shoppingLayout = new javax.swing.GroupLayout(shopping);
        shopping.setLayout(shoppingLayout);
        shoppingLayout.setHorizontalGroup(
            shoppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        shoppingLayout.setVerticalGroup(
            shoppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        getContentPane().add(shopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 750, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMousePressed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMousePressed

    private void closewindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closewindowMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closewindowMousePressed

    private void shirtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shirtMousePressed
        // TODO add your handling code here:
      shirtpage();
    }//GEN-LAST:event_shirtMousePressed

    private void AllMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllMousePressed
        // TODO add your handling code here:
        allpage();
    }//GEN-LAST:event_AllMousePressed

    private void pantMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantMousePressed
        // TODO add your handling code here:
        pantpage();
    }//GEN-LAST:event_pantMousePressed

    private void jewelleryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jewelleryMousePressed
        // TODO add your handling code here:
        jewellerypage();
    }//GEN-LAST:event_jewelleryMousePressed

    private void CartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMousePressed
        // TODO add your handling code here:
        cartpage();
    }//GEN-LAST:event_CartMousePressed

    private void edibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edibleMousePressed
        // TODO add your handling code here:
        ediblepage();
    }//GEN-LAST:event_edibleMousePressed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        new Signin_Up().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMousePressed

    private void SpriteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpriteMousePressed
        // TODO add your handling code here:
        
          String Input=JOptionPane.showInputDialog(this,"Enter Quantity");    
    int Amount = Integer.parseInt(Input);
                   
    if (Amount>0 && count<10 ){
                      cartt1.additem(Amount, "Sprite", 130,count );
               count++;
           }
           else if (count<10){
                JOptionPane.showMessageDialog(this,"Your Cart is filled.","Out of Space",JOptionPane.WARNING_MESSAGE);     
           }
    }//GEN-LAST:event_SpriteMousePressed

    private void pepsiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pepsiMousePressed
        // TODO add your handling code here:
        
          String Input=JOptionPane.showInputDialog(this,"Enter Quantity");    
     int Amount = Integer.parseInt(Input);
            
    if (Amount>0 && count<10 ){
                     cartt1.additem(Amount, "Pepsi", 60,count );
               count++;
           }
           else if (count<10){
                JOptionPane.showMessageDialog(this,"Your Cart is filled.","Out of Space",JOptionPane.WARNING_MESSAGE);     
           }
    }//GEN-LAST:event_pepsiMousePressed

    private void DrpepperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrpepperMousePressed
        // TODO add your handling code here:
        
          String Input=JOptionPane.showInputDialog(this,"Enter Quantity");    
         int Amount = Integer.parseInt(Input);
        
    if (Amount>0 && count<10 ){
                     cartt1.additem(Amount, "Dr.Pepper",200,count );
               count++;
           }
           else if (count<10){
                JOptionPane.showMessageDialog(this,"Your Cart is filled.","Out of Space",JOptionPane.WARNING_MESSAGE);     
           }
    }//GEN-LAST:event_DrpepperMousePressed

    private void doritosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doritosMousePressed
        // TODO add your handling code here:
          String Input=JOptionPane.showInputDialog(this,"Enter Quantity");    
int Amount = Integer.parseInt(Input);
                            
    if (Amount>0 && count<10 ){
                     cartt1.additem(Amount, "Doritos", 150,count );
               count++;
           }
           else if (count<10){
                JOptionPane.showMessageDialog(this,"Your Cart is filled.","Out of Space",JOptionPane.WARNING_MESSAGE);     
           }
    }//GEN-LAST:event_doritosMousePressed

    private void redbullMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redbullMousePressed
        // TODO add your handling code here:
        
          String Input=JOptionPane.showInputDialog(this,"Enter Quantity");    
  int Amount = Integer.parseInt(Input);
                     
    if (Amount>0 && count<10 ){
                      cartt1.additem(Amount, "RedBull", 400,count );
               count++;
           }
           else if (count<10){
                JOptionPane.showMessageDialog(this,"Your Cart is filled.","Out of Space",JOptionPane.WARNING_MESSAGE);     
           }
    }//GEN-LAST:event_redbullMousePressed

    private void LaysMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaysMousePressed
        // TODO add your handling code here:
        
          String Input=JOptionPane.showInputDialog(this,"Enter Quantity");    
   int Amount = Integer.parseInt(Input);
                    
    if (Amount>0 && count<10 ){
                      cartt1.additem(Amount, "Lays(Masala)",40,count );
               count++;
           }
           else if (count<10){
                JOptionPane.showMessageDialog(this,"Your Cart is filled.","Out of Space",JOptionPane.WARNING_MESSAGE);     
           }
    }//GEN-LAST:event_LaysMousePressed

    private void wavyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wavyMousePressed
        // TODO add your handling code here:
        
          String Input=JOptionPane.showInputDialog(this,"Enter Quantity");    
     int Amount = Integer.parseInt(Input);
                  
    if (Amount>0 && count<10 ){
                      cartt1.additem(Amount, "Wavy", 40,count );
               count++;
           }
           else if (count<10){
                JOptionPane.showMessageDialog(this,"Your Cart is filled.","Out of Space",JOptionPane.WARNING_MESSAGE);     
           }
    }//GEN-LAST:event_wavyMousePressed

    

  public void shirtpage(){
    
new Customer_Shirt(user,cartt1,count).setVisible(true);     
this.dispose();
 }
 
 public void jewellerypage(){
 
new Customer_Jewel(user,cartt1,count).setVisible(true);     
this.dispose();
 }
 
 
 public void ediblepage(){
   
 }
 public void cartpage(){
        new Cart(user,cartt1,count).setVisible(true);
        this.dispose();
 }
 
 public void allpage(){
    new Customer_UI(user,cartt1,count).setVisible(true);
 }
 public void pantpage(){

new Customer_Pant(user,cartt1,count).setVisible(true);     
this.dispose();
 }    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_edible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_edible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_edible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_edible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_edible(user,cartt1,count).setVisible(true);
            }
        });
    }
    
     private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } 
        
    }
    
    public static cartThread  cartt1 = new cartThread();
    public static int count;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel All;
    private javax.swing.JPanel Cart;
    private javax.swing.JPanel Drpepper;
    private javax.swing.JPanel Lays;
    private javax.swing.JPanel Sprite;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel allitems2;
    private javax.swing.JPanel allitems3;
    private javax.swing.JPanel closewindow;
    private javax.swing.JPanel doritos;
    private javax.swing.JPanel edible;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel jewellery;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel minimize;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JPanel pant;
    private javax.swing.JPanel pepsi;
    private javax.swing.JPanel redbull;
    private javax.swing.JPanel shirt;
    private javax.swing.JPanel shopping;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel wavy;
    // End of variables declaration//GEN-END:variables
}
