/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anusha.ssupermarket;


import java.awt.event.KeyEvent;
import java.awt.event.KeyAdapter;
import javax.swing.*;
import java.awt.*;
import java.io.*;

import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;


/**
 *
 * @author faraz
 */
public class Signin_Up extends javax.swing.JFrame {

    /**
     * Creates new form Signin_Up
     */
    public String userinfo;
    public Signin_Up() {
        initComponents();
              Login.setVisible(false);
              Lbuttons.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        sidebar = new javax.swing.JPanel();
        RegisterTab = new javax.swing.JPanel();
        RegisterInd = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        LoginTab = new javax.swing.JPanel();
        LoginInd = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        TopBar = new javax.swing.JPanel();
        closewindow = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        minimize = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Userinfo = new javax.swing.JPanel();
        Userlogo = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RegistrationForm = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        register2 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        namef = new javax.swing.JTextField();
        emailf = new javax.swing.JTextField();
        numberf = new javax.swing.JTextField();
        countryf = new javax.swing.JComboBox<>();
        passf = new javax.swing.JPasswordField();
        buttons = new javax.swing.JPanel();
        Register = new javax.swing.JButton();
        REset = new javax.swing.JButton();
        Login = new javax.swing.JPanel();
        Lname = new javax.swing.JLabel();
        Lpass = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        lnamef = new javax.swing.JTextField();
        lpassf = new javax.swing.JPasswordField();
        Lbuttons = new javax.swing.JPanel();
        Loginb = new javax.swing.JButton();
        signupb = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 100, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(23, 35, 51));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterTab.setBackground(new java.awt.Color(41, 57, 80));
        RegisterTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterTabMousePressed(evt);
            }
        });
        RegisterTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout RegisterIndLayout = new javax.swing.GroupLayout(RegisterInd);
        RegisterInd.setLayout(RegisterIndLayout);
        RegisterIndLayout.setHorizontalGroup(
            RegisterIndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        RegisterIndLayout.setVerticalGroup(
            RegisterIndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        RegisterTab.add(RegisterInd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        name1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(242, 242, 242));
        name1.setText("Register");
        RegisterTab.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 73, 34));

        sidebar.add(RegisterTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 110, -1));

        LoginTab.setBackground(new java.awt.Color(23, 35, 51));
        LoginTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginTabMousePressed(evt);
            }
        });
        LoginTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginInd.setOpaque(false);

        javax.swing.GroupLayout LoginIndLayout = new javax.swing.GroupLayout(LoginInd);
        LoginInd.setLayout(LoginIndLayout);
        LoginIndLayout.setHorizontalGroup(
            LoginIndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LoginIndLayout.setVerticalGroup(
            LoginIndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LoginTab.add(LoginInd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        name2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        name2.setForeground(new java.awt.Color(242, 242, 242));
        name2.setText("Login");
        LoginTab.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 73, 34));

        sidebar.add(LoginTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, -1));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 490));

        TopBar.setBackground(new java.awt.Color(77, 128, 216));
        TopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closewindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closewindowMousePressed(evt);
            }
        });
        closewindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_close_window_45px.png"))); // NOI18N
        closewindow.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 50, 50));

        TopBar.add(closewindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 30, 30));

        minimize.setInheritsPopupMenu(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeMousePressed(evt);
            }
        });
        minimize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_minimize_window_45px_1.png"))); // NOI18N
        minimize.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 50, 50));

        TopBar.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 30, 30));

        getContentPane().add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 640, 50));

        Userinfo.setBackground(new java.awt.Color(113, 168, 255));
        Userinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Userlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anusha/ssupermarket/imgs/icons8_user_50px.png"))); // NOI18N
        Userinfo.add(Userlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 62, -1));

        Username.setFont(new java.awt.Font("Google Sans Display Medium", 0, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Guest");
        Userinfo.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 145, 50));

        getContentPane().add(Userinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 280, 110));

        jPanel4.setBackground(new java.awt.Color(62, 120, 207));

        jLabel2.setFont(new java.awt.Font("Google Sans Display", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 35, 51));
        jLabel2.setText("Welcome To ");

        jLabel4.setFont(new java.awt.Font("Google Sans Display", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(23, 35, 51));
        jLabel4.setText("Anusha's Supermarket !");

        jLabel5.setFont(new java.awt.Font("Google Sans Display", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(23, 35, 51));
        jLabel5.setText("Please Register or Login");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 280, 340));

        RegistrationForm.setBackground(new java.awt.Color(77, 128, 250));

        jPanel6.setBackground(new java.awt.Color(77, 128, 250));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register2.setBackground(new java.awt.Color(77, 128, 250));

        name.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(242, 242, 242));
        name.setText("Name");

        pass.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(242, 242, 242));
        pass.setText("Password");

        email.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(242, 242, 242));
        email.setText("Email");

        no.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        no.setForeground(new java.awt.Color(242, 242, 242));
        no.setText("Number");

        country.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        country.setForeground(new java.awt.Color(242, 242, 242));
        country.setText("Country");

        title.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(242, 242, 242));
        title.setText("      REGISTRATION");

        namef.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefActionPerformed(evt);
            }
        });

        emailf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfActionPerformed(evt);
            }
        });

        numberf.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();  // if it's not a number, ignore the event
                }
            }
        });
        numberf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        countryf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        countryf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pakistan", "UAE", "USA", "UK", "Canda" }));

        passf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passf.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > 'z') ) && (c != KeyEvent.VK_BACK_SPACE)) {

                    e.consume();  // if it's not a number, ignore the event
                }
            }
        });

        javax.swing.GroupLayout register2Layout = new javax.swing.GroupLayout(register2);
        register2.setLayout(register2Layout);
        register2Layout.setHorizontalGroup(
            register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register2Layout.createSequentialGroup()
                .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(register2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pass)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(country, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(28, 28, 28)
                        .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailf)
                            .addComponent(passf)
                            .addComponent(namef)
                            .addGroup(register2Layout.createSequentialGroup()
                                .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countryf, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberf, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(register2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        register2Layout.setVerticalGroup(
            register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel6.add(register2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 354, 340));

        buttons.setBackground(new java.awt.Color(77, 128, 250));

        Register.setBackground(new java.awt.Color(62, 120, 207));
        Register.setFont(new java.awt.Font("Google Sans Display Medium", 0, 18)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        REset.setBackground(new java.awt.Color(62, 120, 207));
        REset.setFont(new java.awt.Font("Google Sans Display Medium", 0, 18)); // NOI18N
        REset.setForeground(new java.awt.Color(255, 255, 255));
        REset.setText("Reset");
        REset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REsetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsLayout = new javax.swing.GroupLayout(buttons);
        buttons.setLayout(buttonsLayout);
        buttonsLayout.setHorizontalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(REset)
                .addGap(59, 59, 59))
        );
        buttonsLayout.setVerticalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel6.add(buttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Login.setBackground(new java.awt.Color(77, 128, 250));

        Lname.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        Lname.setForeground(new java.awt.Color(242, 242, 242));
        Lname.setText("Name");

        Lpass.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        Lpass.setForeground(new java.awt.Color(242, 242, 242));
        Lpass.setText("Password");

        title1.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        title1.setForeground(new java.awt.Color(242, 242, 242));
        title1.setText("LOGIN PAGE");

        lnamef.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lnamef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnamefActionPerformed(evt);
            }
        });

        lpassf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passf.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > 'z') ) && (c != KeyEvent.VK_BACK_SPACE)) {

                    e.consume();  // if it's not a number, ignore the event
                }
            }
        });
        lpassf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpassfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lpass)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lpassf)
                    .addComponent(lnamef))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnamef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lpass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpassf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );

        jPanel6.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 354, 340));

        Lbuttons.setBackground(new java.awt.Color(77, 128, 250));

        Loginb.setBackground(new java.awt.Color(62, 120, 207));
        Loginb.setFont(new java.awt.Font("Google Sans Display Medium", 0, 18)); // NOI18N
        Loginb.setForeground(new java.awt.Color(255, 255, 255));
        Loginb.setText("Login");
        Loginb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbActionPerformed(evt);
            }
        });

        signupb.setBackground(new java.awt.Color(62, 120, 207));
        signupb.setFont(new java.awt.Font("Google Sans Display Medium", 0, 18)); // NOI18N
        signupb.setForeground(new java.awt.Color(255, 255, 255));
        signupb.setText("Sign Up");
        signupb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LbuttonsLayout = new javax.swing.GroupLayout(Lbuttons);
        Lbuttons.setLayout(LbuttonsLayout);
        LbuttonsLayout.setHorizontalGroup(
            LbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbuttonsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Loginb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(signupb)
                .addGap(59, 59, 59))
        );
        LbuttonsLayout.setVerticalGroup(
            LbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbuttonsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(LbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Loginb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel6.add(Lbuttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        javax.swing.GroupLayout RegistrationFormLayout = new javax.swing.GroupLayout(RegistrationForm);
        RegistrationForm.setLayout(RegistrationFormLayout);
        RegistrationFormLayout.setHorizontalGroup(
            RegistrationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationFormLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RegistrationFormLayout.setVerticalGroup(
            RegistrationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationFormLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(RegistrationForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 360, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMousePressed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMousePressed

    private void closewindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closewindowMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closewindowMousePressed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed

        String Name = namef.getText(); 
        File check = new File(Name+".json");
        
        if(check.exists())  
        {    resetregister();
            registerpage();
            JOptionPane.showMessageDialog(null, "Account with same name already registered",
      "Invalid Username!", JOptionPane.ERROR_MESSAGE); 
        }
            
        else{
            
        String Pass = String.valueOf(passf.getPassword());
        if(Name.length()>0 && Pass.length()>0)
        {
            
        String Email = emailf.getText();
        String No = numberf.getText();
        JSONObject obj = new JSONObject();
        obj.put("Name",Name);
        obj.put("Pass",Pass);
        obj.put("No",No);    
        obj.put("Email",Email);
        userinfo = obj.get("Name").toString();
            try {
                
  FileWriter file = new FileWriter(Name+".json");
  
  file.write(obj.toString());
file.close();

 JOptionPane.showMessageDialog(null, "You Account has been registered",
      "Registered!", JOptionPane.INFORMATION_MESSAGE); 
 loginpage();
} catch (IOException e1) {
// TODO Auto-generated catch block
e1.printStackTrace();
}}
            

        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void REsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REsetActionPerformed
        // TODO add your handling code here:
        
        resetregister();
    }//GEN-LAST:event_REsetActionPerformed
public void resetregister(){
    namef.setText("");
        passf.setText("");
        emailf.setText("");
        numberf.setText("");
}
    private void RegisterTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterTabMousePressed
        // TODO add your handling code here:
      registerpage();
    }//GEN-LAST:event_RegisterTabMousePressed
public void registerpage(){
      setColor(RegisterTab);

                  register2.setVisible(true);
                  buttons.setVisible(true);
                  Lbuttons.setVisible(false);
                                    Login.setVisible(false);
          RegisterInd.setOpaque(true);        
        resetColor(new JPanel[] {LoginTab},new JPanel[] {LoginInd});

}
    private void LoginTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginTabMousePressed
        // TODO add your handling code here:
        loginpage();
    }//GEN-LAST:event_LoginTabMousePressed

    public void loginpage(){
      setColor(LoginTab);
          Login.setVisible(true);        
          register2.setVisible(false);
          buttons.setVisible(false);
           
                  Lbuttons.setVisible(true);               
          LoginInd.setOpaque(true);
        resetColor(new JPanel[] {RegisterTab},new JPanel[] {RegisterInd});
}
    private void lnamefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnamefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnamefActionPerformed

    private void lpassfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpassfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lpassfActionPerformed

    private void LoginbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbActionPerformed
        // TODO add your handling code here:
           Object obj;
try {
obj = new JSONParser().parse(new FileReader(lnamef.getText()+".json"));
JSONObject read = (JSONObject) obj;

String PASS = read.get("Pass").toString();
String PASSINPUT = String.valueOf(lpassf.getPassword());

if(PASS.equals(PASSINPUT)){
    userinfo=lnamef.getText();
          new Customer_UI(userinfo,count).setVisible(true);
        dispose();

}
else{
   JOptionPane.showMessageDialog(null, "Invalid Username or Password!!",
      "ERROR!", JOptionPane.ERROR_MESSAGE); 
}   
} catch (IOException | ParseException e1) {
 JOptionPane.showMessageDialog(null, "Invalid Username or Password!!",
      "ERROR!", JOptionPane.ERROR_MESSAGE); 
}        
        
    }//GEN-LAST:event_LoginbActionPerformed

    private void signupbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbActionPerformed
        // TODO add your handling code here:
    registerpage();
    }//GEN-LAST:event_signupbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signin_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signin_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signin_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signin_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signin_Up().setVisible(true);
            }
        });
    }
    
     private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
public static int count;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lbuttons;
    private javax.swing.JLabel Lname;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel LoginInd;
    private javax.swing.JPanel LoginTab;
    private javax.swing.JButton Loginb;
    private javax.swing.JLabel Lpass;
    private javax.swing.JButton REset;
    private javax.swing.JButton Register;
    private javax.swing.JPanel RegisterInd;
    private javax.swing.JPanel RegisterTab;
    private javax.swing.JPanel RegistrationForm;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel Userinfo;
    private javax.swing.JLabel Userlogo;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel closewindow;
    private javax.swing.JLabel country;
    private javax.swing.JComboBox<String> countryf;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailf;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lnamef;
    private javax.swing.JPasswordField lpassf;
    private javax.swing.JPanel minimize;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JTextField namef;
    private javax.swing.JLabel no;
    private javax.swing.JTextField numberf;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passf;
    private javax.swing.JPanel register2;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton signupb;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
